// <auto-generated />
namespace ShoeWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class updateSizeToDb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateSizeToDb));
        
        string IMigrationMetadata.Id
        {
            get { return "202410180146279_updateSizeToDb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
