// <auto-generated />
namespace ShoeWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class updateOrder_02 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateOrder_02));
        
        string IMigrationMetadata.Id
        {
            get { return "202411261512425_updateOrder_02"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
